export const SidebarMenu = [
    {
      id: 1,
      title: "Dashboard",
      icon: "house",
      url: "/",
      isDrop: false,
    },
    {
      id: 2,
      title: "Registration",
      icon: "registered",
      isDrop: true,
      isCollapse: false,
      collapse: "#panelsStayOpen-collapseOne",
      area: "panelsStayOpen-collapseOne",
      dropMenus: [
        { id: 1, url: "/student/registration-certificate", name: "Registration Certificate" },
      ],
    },
    {
      id: 3,
      title: "Security Module",
      icon: "lock",
      isDrop: true,
      isCollapse: false,
      collapse: "#panelsStayOpen-collapseOne",
      area: "panelsStayOpen-collapseOne",
      dropMenus: [
        { id: 1, url: "/user/creation", name: "Creation of User" },
        { id: 2, url: "/user/portal-admin", name: "Portal Admin" },
        { id: 3, url: "/user/change-password", name: "Change Login Password" },
        { id: 4, url: "/user/reset-password", name: "Reset Login Password" },
        { id: 5, url: "/user/role-creation", name: "Creation of Roles" },
      ],
    },
    {
      id: 5,
      title: "Master Module",
      icon: "cog",
      isDrop: true,
      isCollapse: false,
      collapse: "#masterSubmenu",
      area: "masterSubmenu",
      dropMenus: [
        { id: 1, url: "/master/company-master", name: "Modify Company Master" },
        { id: 2, url: "/master/code-master", name: "Code Master Maintenance" },
        { id: 3, url: "/master/group-master", name: "Group Master Maintenance" },
        { id: 4, url: "/master/group-department", name: "Group-Department Maintenance" },
        { id: 5, url: "/master/earning-deduction", name: "View Earning/Deduction Master" },
        { id: 6, url: "/master/company-payitem", name: "Company wise PayItem" },
        { id: 7, url: "/master/grade-payitem", name: "Grade wise PayItem" },
        { id: 8, url: "/master/employee-payitem", name: "Employee wise PayItem" },
        { id: 9, url: "/master/employee-master", name: "Employee Master Maintenance" },
        { id: 10, url: "/master/company-rules", name: "Company Rules Maintenance" },
        { id: 11, url: "/master/itax-form-items", name: "Modify ITax Form Items" },
        { id: 12, url: "/master/itax-income-age", name: "ITax % Income and Age wise" },
        { id: 13, url: "/master/itax-slab-section", name: "Modify ITax Slab Section wise" },
        { id: 14, url: "/master/ptax-slab", name: "PTax Slab Master Maintenance" },
        { id: 15, url: "/master/electricity-rate", name: "Electricity Rate Master Maintenance" },
        { id: 16, url: "/master/time-office-section", name: "Time Office Section Maintenance" },
        { id: 17, url: "/master/time-office-rack", name: "Time Office Rack Allocation" },
        { id: 18, url: "/master/canteen-rate", name: "Canteen Rate Maintenance" },
        { id: 19, url: "/master/department-master", name: "Department Master Maintenance" },
        { id: 20, url: "/master/grade-designation", name: "Gradewise-Designation Maintenance" },
        { id: 21, url: "/master/department-salary-head", name: "Departmentwise Salary Head" },
        { id: 22, url: "/master/pay-scale", name: "Pay Scale Maintenance" },
        { id: 23, url: "/master/pd-change", name: "PD Change" },
        { id: 24, url: "/master/pf-account-ledger", name: "PF Account Ledger Master" },
        { id: 25, url: "/master/pf-interest-rate", name: "PF Interest Rate Master" },
        { id: 26, url: "/master/pf-nominee-detail", name: "PF Nominee Detail" },
        { id: 27, url: "/master/pf-family-member", name: "PF Family Member Detail" },
        { id: 28, url: "/master/pf-investment-details", name: "PF Cat/SubCat Investment Details" },
        { id: 29, url: "/master/pf-employee", name: "PF Employee Master" },
        { id: 30, url: "/master/pf-balance-sheet", name: "PF Balance Sheet Mapping" },
        { id: 31, url: "/master/pf-general-ledger", name: "PF General Ledger Mapping" },
        { id: 32, url: "/master/bonus-rules", name: "Bonus Rules" },
      ],
    },
    {
      id: 6,
      title: "Transaction Module",
      icon: "exchange",
      isDrop: true,
      isCollapse: false,
      collapse: "#transactionSubmenu",
      area: "transactionSubmenu",
      dropMenus: [
        { id: 1, url: "/transaction/electricity-reading", name: "Quarterly Electricity Meter Reading" },
        { id: 2, url: "/transaction/monthly-attendance", name: "Monthly Attendance" },
        { id: 3, url: "/transaction/monthly-ccs", name: "Monthly CCS Maintenance" },
        { id: 4, url: "/transaction/monthly-mcs", name: "Monthly MCS Maintenance" },
        { id: 5, url: "/transaction/monthly-single-wages", name: "Monthly Single Wages Maintenance" },
        { id: 6, url: "/transaction/monthly-night-allowance", name: "Monthly Night Allowance" },
        { id: 7, url: "/transaction/mass-upload", name: "Mass Upload" },
        { id: 8, url: "/transaction/encashment-el", name: "Encashment of EL" },
        { id: 9, url: "/transaction/school-vehicle-maintenance", name: "School/Vehicle Bus Maintenance" },
        { id: 10, url: "/transaction/recovery-loans-advances", name: "Recovery of Loans and Advances" },
        { id: 11, url: "/transaction/monthly-lip", name: "Monthly LIP Maintenance" },
        { id: 12, url: "/transaction/quater-allocation-deallocation", name: "Quater Allocation / DeAllocation" },
        { id: 13, url: "/transaction/employee-promotion-appointment", name: "Employee Promotion/Appointment" },
        { id: 14, url: "/transaction/monthly-hostel-charge", name: "Monthly Hostel Charge Maintenance" },
        { id: 15, url: "/transaction/ltc-maintenance", name: "LTC Maintenance" },
        { id: 16, url: "/transaction/monthly-supplimentory-attendance", name: "Monthly Supplimentory Attendance" },
        { id: 17, url: "/transaction/it-declare-form-entry", name: "IT Declare Form Entry FY 2023-24" },
        { id: 18, url: "/transaction/employee-pay-item-entry", name: "Employee Pay Item Entry" },
        { id: 19, url: "/transaction/hra-arrear-retired-employee", name: "HRA Arrear For Retired Employee" },
        { id: 20, url: "/transaction/pf-receipt-voucher", name: "PF Receipt Voucher" },
        { id: 21, url: "/transaction/pf-payment-voucher", name: "PF Payment Voucher" },
        { id: 22, url: "/transaction/pf-journal-voucher", name: "PF Journal Voucher" },
        { id: 23, url: "/transaction/pf-monthly-loans-refundable", name: "PF Monthly Loans (Refundable)" },
        { id: 24, url: "/transaction/pf-monthly-contribution", name: "PF Monthly Contribution" },
        { id: 25, url: "/transaction/pf-investment-details", name: "PF Investment Details" },
        { id: 26, url: "/transaction/etds-challan-details", name: "ETDS Challan Details" },
        { id: 27, url: "/transaction/pf-arrear-pension", name: "PF Arrear Pension" },
        { id: 28, url: "/transaction/pf-monthly-loans-non-refundable", name: "PF Monthly Loans (Non-Refundable)" },
        { id: 29, url: "/transaction/publish-pf-ledger", name: "Publish PF Ledger" },
        { id: 30, url: "/transaction/ccs-house-building-loan", name: "CCS House Building Loan" },
        { id: 31, url: "/transaction/manual-salary", name: "Manual Salary" },
        { id: 32, url: "/transaction/pf-brs-entry", name: "PF BRS Entry" },
        { id: 33, url: "/transaction/pf-brs-opening-balance", name: "PF BRS Opening Balance" },
        { id: 34, url: "/transaction/click-submit-eps", name: "Click to Submit EPS Option" },
      ],
    },
    {
      id: 7,
      title: "Processing Module",
      icon: "cog",
      isDrop: true,
      isCollapse: false,
      collapse: "#processingSubmenu",
      area: "processingSubmenu",
      dropMenus: [
        { id: 1, url: "/processing/run-payroll", name: "RUN PAYROLL" },
        { id: 2, url: "/processing/delete-payroll", name: "DELETE PAYROLL" },
        { id: 3, url: "/processing/month-end-processing", name: "MONTH END Processing" },
        { id: 4, url: "/processing/arrear-processing", name: "ARREAR Processing" },
        { id: 5, url: "/processing/generate-form-16", name: "Generate Manual Form 16" },
        { id: 6, url: "/processing/yearly-tax-calculation", name: "Process Yearly Tax Calculation" },
        { id: 7, url: "/processing/delete-arrear", name: "DELETE ARREAR" },
        { id: 8, url: "/processing/pd-update", name: "PD Update" },
        { id: 9, url: "/processing/pf-ledger-processing", name: "PF Ledger Processing" },
        { id: 10, url: "/processing/pf-trial-balance-processing", name: "PF Trial Balance Processing" },
        { id: 11, url: "/processing/pf-year-end-processing", name: "PF Year End Processing" },
        { id: 12, url: "/processing/pf-general-ledger-year-end", name: "PF (GENERAL LEDGER) Year End Processing" },
        { id: 13, url: "/processing/pf-ledger-retiring-employee", name: "PF Ledger Processing (Retiring Employee)" },
        { id: 14, url: "/processing/pf-bill-processing", name: "PF Bill Processing" },
        { id: 15, url: "/processing/pf-monthly-trial-balance", name: "PF Monthly Trial Balance Processing" },
        { id: 16, url: "/processing/pf-yearly-cash-trial-balance", name: "PF Yearly Cash Trial Balance Processing" },
        { id: 17, url: "/processing/pf-monthly-cash-trial-balance", name: "PF Monthly Cash Trial Balance Processing" },
        { id: 18, url: "/processing/release-payslip", name: "RELEASE PAYSLIP" },
      ],
    },
    // {
    //   id: 8,
    //   title: "Report Module",
    //   icon: "file-alt",
    //   isDrop: true,
    //   isCollapse: false,
    //   collapse: "#reportSubmenu",
    //   area: "reportSubmenu",
    //   dropMenus: [
    //     { id: 1, url: "/reports/delete-payroll", name: "DELETE PAYROLL" },
    //     { id: 2, url: "/reports/month-end-processing", name: "MONTH END Processing" },
    //     { id: 3, url: "/reports/arrear-processing", name: "ARREAR Processing" },
    //     { id: 4, url: "/reports/generate-form-16", name: "Generate Manual Form 16" },
    //     { id: 5, url: "/reports/yearly-tax-calculation", name: "Process Yearly Tax Calculation" },
    //     { id: 6, url: "/reports/delete-arrear", name: "DELETE ARREAR" },
    //     { id: 7, url: "/reports/pd-update", name: "PD Update" },
    //     { id: 8, url: "/reports/pf-ledger-processing", name: "PF Ledger Processing" },
    //     { id: 9, url: "/reports/pf-trial-balance-processing", name: "PF Trial Balance Processing" },
    //     { id: 10, url: "/reports/pf-year-end-processing", name: "PF Year End Processing" },
    //     { id: 11, url: "/reports/pf-general-ledger-year-end", name: "PF (GENERAL LEDGER) Year End Processing" },
    //     { id: 12, url: "/reports/pf-ledger-retiring-employee", name: "PF Ledger Processing (Retiring Employee)" },
    //     { id: 13, url: "/reports/pf-bill-processing", name: "PF Bill Processing" },
    //     { id: 14, url: "/reports/pf-monthly-trial-balance", name: "PF Monthly Trial Balance Processing" },
    //     { id: 15, url: "/reports/pf-yearly-cash-trial-balance", name: "PF Yearly Cash Trial Balance Processing" },
    //     { id: 16, url: "/reports/pf-monthly-cash-trial-balance", name: "PF Monthly Cash Trial Balance Processing" },
    //     { id: 17, url: "/reports/release-payslip", name: "RELEASE PAYSLIP" },
    //     // Add more report items here as needed...
    //   ],
    // },
    // {
    //   id: 9,
    //   title: "Attendance Module",
    //   icon: "user",
    //   isDrop: true,
    //   isCollapse: false,
    //   collapse: "#attendanceSubmenu",
    //   area: "attendanceSubmenu",
    //   dropMenus: [
    //     { id: 1, url: "/attendance/leave-application", name: "Leave Application" },
    //     { id: 2, url: "/attendance/tour-application", name: "Tour Application" },
    //     { id: 3, url: "/attendance/view-leave-status", name: "View Leave Status" },
    //     { id: 4, url: "/attendance/view-tour-status", name: "View Tour Status" },
    //     { id: 5, url: "/attendance/view-punch-in-out", name: "View Punch In Out" },
    //     { id: 6, url: "/attendance/shift-change-application", name: "Shift Change Application" },
    //     { id: 7, url: "/attendance/reporting-person-maintenance", name: "Reporting Person Maintenance" },
    //     { id: 8, url: "/attendance/leave-rule", name: "Leave Rule" },
    //     { id: 9, url: "/attendance/company-holiday-list", name: "Company wise Holiday List" },
    //     { id: 10, url: "/attendance/employee-offday-list", name: "Employee wise OffDay List" },
    //     { id: 11, url: "/attendance/daily-attendance-maintenance", name: "Daily Attendance Sheet Maintenance" },
    //     { id: 12, url: "/attendance/shift-timing-maintenance", name: "Shift Timing Maintenance" },
    //     { id: 13, url: "/attendance/employee-service-rule-maintenance", name: "Emp Service Rule and Roaster Maintenance" },
    //     { id: 14, url: "/attendance/employee-supervisor-maintenance", name: "Employee Supervisor Maintenance" },
    //     { id: 15, url: "/attendance/generate-monthly-payroll-data", name: "Generate Monthly Payroll Data" },
    //     { id: 16, url: "/attendance/view-leave-balance", name: "View Leave Balance" },
    //     { id: 17, url: "/attendance/populate-attendance", name: "Populate Attendance" },
    //     { id: 18, url: "/attendance/send-to-payroll", name: "Send To Payroll / Back" },
    //     { id: 19, url: "/attendance/attendance-approval", name: "Attendance Approval" },
    //     { id: 20, url: "/attendance/leave-approval", name: "Leave Approval" },
    //     { id: 21, url: "/attendance/tour-approval", name: "Tour Approval" },
    //     { id: 22, url: "/attendance/shift-change-approval", name: "Shift Change Approval" },
    //     // Add more attendance module items here as needed...
    //   ],
    // },
  ];
  