 
export const initialData = {
  stnSupplyNo: "",
  stnSupplyDate: "",
  stnIndentNo: "", 
  issuedByEmpCode: "",
  issuedByEmpName: "",
  stnIssuedDate: "",
  priceStoreLedgerIPostBy: "",
  priStrLedIssByEmpName: "",
  priceStoreLedgerIPostDate: "",
  stnReceivedBy: "",
  receivedByEmpName: "",
  stnReceivedDate: "",
  priceStoreLedgerRPostBy: "",
  priStrLedRecByEmpName: "",
  priceStoreLedgerRPostDate: "",
  stnSupplyStatus: "",
  stnIndentDate: "",
  indentingDivision: "",
  indentingDivisionName: "",
  supplyingDivision: "",
  supplyingDivisionName: "",
  transactionCodeId: "",
  transactionDescIndentingDiv: "",
  transactionCodeSd: "",
  transactionDescSupplyingDiv: "",
  stnIndentedBy: "",
  indentedByEmpCode: "",
  indentedByEmpName: "",
  stnIndentedDate: "",
  groupNo: "",
  functionalGroupName: "",
  subGroupNo: "",
  subGroupName: "",
  stnSupplyChildList: [
    {
      stnSupplySrlNo: "",
      stnIndentSrlNo: "",
      itemCode: "",
      itemDescription: "",
      folioNo: null,
      unitCode: "",
      unitDescription: "",
      wtAvgRate: '0',
      reqQtyInNumber: null,
      qtyIssuedOnStn: 0,
      earlierBalanceStock: null,
      qtyIssuedOnStn: null,
      finalBalanceStock: null,
      rate: null,
      amount: null,
      remarks: "",
      priceStoreLedgerIFolioNo: "",
      priceStoreLedgerRFolioNo: "",
      supplyItem: "",
      itemDescSupply: "",
      folioNoSupply: null,
      supplyBinBalance: null
    }
  ] 
};

 
       